import type { Metadata } from "next";
import "./globals.css";
import Navigation from "./component/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head />
      <body className="flex flex-col" suppressHydrationWarning={true}>
        <div>{children}</div>
      </body>
    </html>
  );
}
