import type { Metadata } from "next";
import "../globals.css";
import Navigation from "../component/navigation";
import Header from "../component/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="background w-screen h-screen flex flex-row">
      <Navigation />
      <div className="flex flex-col ml-4 flex-1">
        <Header />
        {children}
      </div>
    </div>
  );
}
